name = "Foundation"
defaultTargets = [
  "Foundation",
  "book",
  "Zoo_Arith",
  "Zoo_SetTheory",
  "Zoo_Modal",
  "Zoo_InterpretabilityLogic",
  "Zoo_Propositional",
]

[leanOptions]
pp.unicode.fun = true
weak.linter.flexible = true
weak.linter.refine = true
weak.linter.oldObtain = true
weak.linter.style.multiGoal = true

[[require]]
scope = "leanprover-community"
name = "mathlib"

[[require]]
scope = "leanprover"
name = "doc-gen4"

[[require]]
scope = "leanprover"
name = "verso"

[[lean_lib]]
name = "Foundation"

[[lean_exe]]
name = "Zoo_Arith"
root = "Zoo.Arith"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_SetTheory"
root = "Zoo.SetTheory"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_Modal"
root = "Zoo.Modal"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_InterpretabilityLogic"
root = "Zoo.InterpretabilityLogic"
supportInterpreter = true

[[lean_exe]]
name = "Zoo_Propositional"
root = "Zoo.Propositional"
supportInterpreter = true

[[lean_lib]]
name = "Zoo"

[[lean_lib]]
name = "Book"

[[lean_exe]]
name = "book"
root = "Book.Book"
