name = "Foundation"
defaultTargets = ["Foundation"]

[leanOptions]
pp.unicode.fun = true
weak.linter.flexible = true
weak.linter.refine = true
weak.linter.oldObtain = true
weak.linter.style.multiGoal = true

[[require]]
scope = "leanprover-community"
name = "mathlib"
rev = "f317236f66fce00be8a8e0f01cdd31619909f887"

[[require]]
scope = "leanprover"
name = "doc-gen4"

[[lean_lib]]
name = "Foundation"
