name = "Foundation"
defaultTargets = ["Foundation"]

[leanOptions]
pp.unicode.fun = true
weak.linter.flexible = true
weak.linter.refine = true
weak.linter.oldObtain = true
weak.linter.style.multiGoal = true

[[require]]
scope = "leanprover-community"
name = "mathlib"

[[require]]
scope = "leanprover"
name = "doc-gen4"

[[lean_lib]]
name = "Foundation"
